Repository sahilsaha7773/SpotLight, pull requests merged in 2022-02, with the labels that each got.

#16 added artist popularity in the artist card
  src/components/TopArtists.js
Labels: JWOC, easy

#17 linked spotify artist page url with artist card
  src/components/TopArtists.js
Labels: JWOC, easy

#21 Designing the Top Genre Section
  package-lock.json
  package.json
  src/Pages/Home.js
  src/index.css
  src/styles/topGenre.css
Labels: JWOC, hard

#27 Made a Logo
  Logos/SPOTLIGHT-DARK-1.png
  Logos/SPOTLIGHT-DARK-2.png
  Logos/SPOTLIGHT.png
Labels: JWOC, medium

#30 Nowplaying
  src/Pages/Home.js
  src/components/Current.js
  src/components/TopArtists.js
  src/styles/currentlyPlaying.module.css
  src/styles/home.module.css
  src/styles/topArtists.module.css
Labels: JWOC, hard
